quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=hallen
quarkus.datasource.password=hallen
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hallen

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

quarkus.datasource.devservices.enabled=false

quarkus.swagger-ui.always-include=true


############################################

